# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.embed_response import EmbedResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestEmbedResponse(unittest.TestCase):
    """EmbedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmbedResponse(self):
        """Test EmbedResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.embed_response.EmbedResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
