# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.quality_response_metadata import QualityResponseMetadata  # noqa: E501
from swagger_client.rest import ApiException


class TestQualityResponseMetadata(unittest.TestCase):
    """QualityResponseMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQualityResponseMetadata(self):
        """Test QualityResponseMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.quality_response_metadata.QualityResponseMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
