# coding: utf-8

# flake8: noqa
"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.all_of_quality_answer_result_metrics import AllOfQualityAnswerResultMetrics
from swagger_client.models.all_of_quality_answer_result_roles_profile import AllOfQualityAnswerResultRolesProfile
from swagger_client.models.all_of_tutor_response_roles_profile import AllOfTutorResponseRolesProfile
from swagger_client.models.embed_request import EmbedRequest
from swagger_client.models.embed_response import EmbedResponse
from swagger_client.models.embed_response_embeddings import EmbedResponseEmbeddings
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.error_response_error import ErrorResponseError
from swagger_client.models.quality_answer_input import QualityAnswerInput
from swagger_client.models.quality_answer_result import QualityAnswerResult
from swagger_client.models.quality_request import QualityRequest
from swagger_client.models.quality_response import QualityResponse
from swagger_client.models.quality_response_metadata import QualityResponseMetadata
from swagger_client.models.roles_profile import RolesProfile
from swagger_client.models.roles_profile_request import RolesProfileRequest
from swagger_client.models.roles_profile_response import RolesProfileResponse
from swagger_client.models.roles_profile_response_metadata import RolesProfileResponseMetadata
from swagger_client.models.roles_profile_top_roles import RolesProfileTopRoles
from swagger_client.models.savant_quality_metrics import SavantQualityMetrics
from swagger_client.models.tutor_request import TutorRequest
from swagger_client.models.tutor_response import TutorResponse
from swagger_client.models.tutor_response_candidates import TutorResponseCandidates
