# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EmbedResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'model': 'str',
        'dimension': 'int',
        'embeddings': 'list[EmbedResponseEmbeddings]'
    }

    attribute_map = {
        'version': 'version',
        'model': 'model',
        'dimension': 'dimension',
        'embeddings': 'embeddings'
    }

    def __init__(self, version=None, model=None, dimension=None, embeddings=None):  # noqa: E501
        """EmbedResponse - a model defined in Swagger"""  # noqa: E501
        self._version = None
        self._model = None
        self._dimension = None
        self._embeddings = None
        self.discriminator = None
        if version is not None:
            self.version = version
        if model is not None:
            self.model = model
        if dimension is not None:
            self.dimension = dimension
        if embeddings is not None:
            self.embeddings = embeddings

    @property
    def version(self):
        """Gets the version of this EmbedResponse.  # noqa: E501


        :return: The version of this EmbedResponse.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this EmbedResponse.


        :param version: The version of this EmbedResponse.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def model(self):
        """Gets the model of this EmbedResponse.  # noqa: E501


        :return: The model of this EmbedResponse.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this EmbedResponse.


        :param model: The model of this EmbedResponse.  # noqa: E501
        :type: str
        """

        self._model = model

    @property
    def dimension(self):
        """Gets the dimension of this EmbedResponse.  # noqa: E501

        Embedding dimension if requested.  # noqa: E501

        :return: The dimension of this EmbedResponse.  # noqa: E501
        :rtype: int
        """
        return self._dimension

    @dimension.setter
    def dimension(self, dimension):
        """Sets the dimension of this EmbedResponse.

        Embedding dimension if requested.  # noqa: E501

        :param dimension: The dimension of this EmbedResponse.  # noqa: E501
        :type: int
        """

        self._dimension = dimension

    @property
    def embeddings(self):
        """Gets the embeddings of this EmbedResponse.  # noqa: E501


        :return: The embeddings of this EmbedResponse.  # noqa: E501
        :rtype: list[EmbedResponseEmbeddings]
        """
        return self._embeddings

    @embeddings.setter
    def embeddings(self, embeddings):
        """Sets the embeddings of this EmbedResponse.


        :param embeddings: The embeddings of this EmbedResponse.  # noqa: E501
        :type: list[EmbedResponseEmbeddings]
        """

        self._embeddings = embeddings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EmbedResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmbedResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
