# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EmbedRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'texts': 'list[str]',
        'normalize_embeddings': 'bool',
        'return_dim': 'bool'
    }

    attribute_map = {
        'texts': 'texts',
        'normalize_embeddings': 'normalize_embeddings',
        'return_dim': 'return_dim'
    }

    def __init__(self, texts=None, normalize_embeddings=True, return_dim=True):  # noqa: E501
        """EmbedRequest - a model defined in Swagger"""  # noqa: E501
        self._texts = None
        self._normalize_embeddings = None
        self._return_dim = None
        self.discriminator = None
        self.texts = texts
        if normalize_embeddings is not None:
            self.normalize_embeddings = normalize_embeddings
        if return_dim is not None:
            self.return_dim = return_dim

    @property
    def texts(self):
        """Gets the texts of this EmbedRequest.  # noqa: E501

        List of texts to embed.  # noqa: E501

        :return: The texts of this EmbedRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._texts

    @texts.setter
    def texts(self, texts):
        """Sets the texts of this EmbedRequest.

        List of texts to embed.  # noqa: E501

        :param texts: The texts of this EmbedRequest.  # noqa: E501
        :type: list[str]
        """
        if texts is None:
            raise ValueError("Invalid value for `texts`, must not be `None`")  # noqa: E501

        self._texts = texts

    @property
    def normalize_embeddings(self):
        """Gets the normalize_embeddings of this EmbedRequest.  # noqa: E501

        Whether to L2-normalize embeddings.  # noqa: E501

        :return: The normalize_embeddings of this EmbedRequest.  # noqa: E501
        :rtype: bool
        """
        return self._normalize_embeddings

    @normalize_embeddings.setter
    def normalize_embeddings(self, normalize_embeddings):
        """Sets the normalize_embeddings of this EmbedRequest.

        Whether to L2-normalize embeddings.  # noqa: E501

        :param normalize_embeddings: The normalize_embeddings of this EmbedRequest.  # noqa: E501
        :type: bool
        """

        self._normalize_embeddings = normalize_embeddings

    @property
    def return_dim(self):
        """Gets the return_dim of this EmbedRequest.  # noqa: E501

        Whether to include the embedding dimension in the response.  # noqa: E501

        :return: The return_dim of this EmbedRequest.  # noqa: E501
        :rtype: bool
        """
        return self._return_dim

    @return_dim.setter
    def return_dim(self, return_dim):
        """Sets the return_dim of this EmbedRequest.

        Whether to include the embedding dimension in the response.  # noqa: E501

        :param return_dim: The return_dim of this EmbedRequest.  # noqa: E501
        :type: bool
        """

        self._return_dim = return_dim

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EmbedRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmbedRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
