# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QualityRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'prompt': 'str',
        'answers': 'list[QualityAnswerInput]',
        'include_roles_profile': 'bool',
        'return_top_k': 'int',
        'normalize_scores': 'bool'
    }

    attribute_map = {
        'prompt': 'prompt',
        'answers': 'answers',
        'include_roles_profile': 'include_roles_profile',
        'return_top_k': 'return_top_k',
        'normalize_scores': 'normalize_scores'
    }

    def __init__(self, prompt=None, answers=None, include_roles_profile=True, return_top_k=None, normalize_scores=True):  # noqa: E501
        """QualityRequest - a model defined in Swagger"""  # noqa: E501
        self._prompt = None
        self._answers = None
        self._include_roles_profile = None
        self._return_top_k = None
        self._normalize_scores = None
        self.discriminator = None
        self.prompt = prompt
        self.answers = answers
        if include_roles_profile is not None:
            self.include_roles_profile = include_roles_profile
        if return_top_k is not None:
            self.return_top_k = return_top_k
        if normalize_scores is not None:
            self.normalize_scores = normalize_scores

    @property
    def prompt(self):
        """Gets the prompt of this QualityRequest.  # noqa: E501

        Prompt or question that produced the candidate answers.  # noqa: E501

        :return: The prompt of this QualityRequest.  # noqa: E501
        :rtype: str
        """
        return self._prompt

    @prompt.setter
    def prompt(self, prompt):
        """Sets the prompt of this QualityRequest.

        Prompt or question that produced the candidate answers.  # noqa: E501

        :param prompt: The prompt of this QualityRequest.  # noqa: E501
        :type: str
        """
        if prompt is None:
            raise ValueError("Invalid value for `prompt`, must not be `None`")  # noqa: E501

        self._prompt = prompt

    @property
    def answers(self):
        """Gets the answers of this QualityRequest.  # noqa: E501

        Candidate answers to evaluate.  # noqa: E501

        :return: The answers of this QualityRequest.  # noqa: E501
        :rtype: list[QualityAnswerInput]
        """
        return self._answers

    @answers.setter
    def answers(self, answers):
        """Sets the answers of this QualityRequest.

        Candidate answers to evaluate.  # noqa: E501

        :param answers: The answers of this QualityRequest.  # noqa: E501
        :type: list[QualityAnswerInput]
        """
        if answers is None:
            raise ValueError("Invalid value for `answers`, must not be `None`")  # noqa: E501

        self._answers = answers

    @property
    def include_roles_profile(self):
        """Gets the include_roles_profile of this QualityRequest.  # noqa: E501

        Whether to include roles profile for each answer.  # noqa: E501

        :return: The include_roles_profile of this QualityRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_roles_profile

    @include_roles_profile.setter
    def include_roles_profile(self, include_roles_profile):
        """Sets the include_roles_profile of this QualityRequest.

        Whether to include roles profile for each answer.  # noqa: E501

        :param include_roles_profile: The include_roles_profile of this QualityRequest.  # noqa: E501
        :type: bool
        """

        self._include_roles_profile = include_roles_profile

    @property
    def return_top_k(self):
        """Gets the return_top_k of this QualityRequest.  # noqa: E501

        Number of top-ranked answers to return. If omitted, returns all answers sorted by score.   # noqa: E501

        :return: The return_top_k of this QualityRequest.  # noqa: E501
        :rtype: int
        """
        return self._return_top_k

    @return_top_k.setter
    def return_top_k(self, return_top_k):
        """Sets the return_top_k of this QualityRequest.

        Number of top-ranked answers to return. If omitted, returns all answers sorted by score.   # noqa: E501

        :param return_top_k: The return_top_k of this QualityRequest.  # noqa: E501
        :type: int
        """

        self._return_top_k = return_top_k

    @property
    def normalize_scores(self):
        """Gets the normalize_scores of this QualityRequest.  # noqa: E501

        Whether to include a normalized score in [0, 1].  # noqa: E501

        :return: The normalize_scores of this QualityRequest.  # noqa: E501
        :rtype: bool
        """
        return self._normalize_scores

    @normalize_scores.setter
    def normalize_scores(self, normalize_scores):
        """Sets the normalize_scores of this QualityRequest.

        Whether to include a normalized score in [0, 1].  # noqa: E501

        :param normalize_scores: The normalize_scores of this QualityRequest.  # noqa: E501
        :type: bool
        """

        self._normalize_scores = normalize_scores

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QualityRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QualityRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
