# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QualityResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'prompt': 'str',
        'ranked_answers': 'list[QualityAnswerResult]',
        'metadata': 'QualityResponseMetadata'
    }

    attribute_map = {
        'version': 'version',
        'prompt': 'prompt',
        'ranked_answers': 'ranked_answers',
        'metadata': 'metadata'
    }

    def __init__(self, version=None, prompt=None, ranked_answers=None, metadata=None):  # noqa: E501
        """QualityResponse - a model defined in Swagger"""  # noqa: E501
        self._version = None
        self._prompt = None
        self._ranked_answers = None
        self._metadata = None
        self.discriminator = None
        if version is not None:
            self.version = version
        if prompt is not None:
            self.prompt = prompt
        if ranked_answers is not None:
            self.ranked_answers = ranked_answers
        if metadata is not None:
            self.metadata = metadata

    @property
    def version(self):
        """Gets the version of this QualityResponse.  # noqa: E501


        :return: The version of this QualityResponse.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this QualityResponse.


        :param version: The version of this QualityResponse.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def prompt(self):
        """Gets the prompt of this QualityResponse.  # noqa: E501


        :return: The prompt of this QualityResponse.  # noqa: E501
        :rtype: str
        """
        return self._prompt

    @prompt.setter
    def prompt(self, prompt):
        """Sets the prompt of this QualityResponse.


        :param prompt: The prompt of this QualityResponse.  # noqa: E501
        :type: str
        """

        self._prompt = prompt

    @property
    def ranked_answers(self):
        """Gets the ranked_answers of this QualityResponse.  # noqa: E501

        Answers sorted by descending quality score.  # noqa: E501

        :return: The ranked_answers of this QualityResponse.  # noqa: E501
        :rtype: list[QualityAnswerResult]
        """
        return self._ranked_answers

    @ranked_answers.setter
    def ranked_answers(self, ranked_answers):
        """Sets the ranked_answers of this QualityResponse.

        Answers sorted by descending quality score.  # noqa: E501

        :param ranked_answers: The ranked_answers of this QualityResponse.  # noqa: E501
        :type: list[QualityAnswerResult]
        """

        self._ranked_answers = ranked_answers

    @property
    def metadata(self):
        """Gets the metadata of this QualityResponse.  # noqa: E501


        :return: The metadata of this QualityResponse.  # noqa: E501
        :rtype: QualityResponseMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this QualityResponse.


        :param metadata: The metadata of this QualityResponse.  # noqa: E501
        :type: QualityResponseMetadata
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QualityResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QualityResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
