# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RerankCandidate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'candidate_id': 'str',
        'text': 'str',
        'ranks': 'dict(str, int)'
    }

    attribute_map = {
        'candidate_id': 'candidate_id',
        'text': 'text',
        'ranks': 'ranks'
    }

    def __init__(self, candidate_id=None, text=None, ranks=None):  # noqa: E501
        """RerankCandidate - a model defined in Swagger"""  # noqa: E501
        self._candidate_id = None
        self._text = None
        self._ranks = None
        self.discriminator = None
        self.candidate_id = candidate_id
        self.text = text
        if ranks is not None:
            self.ranks = ranks

    @property
    def candidate_id(self):
        """Gets the candidate_id of this RerankCandidate.  # noqa: E501

        Stable identifier for the candidate document or answer.  # noqa: E501

        :return: The candidate_id of this RerankCandidate.  # noqa: E501
        :rtype: str
        """
        return self._candidate_id

    @candidate_id.setter
    def candidate_id(self, candidate_id):
        """Sets the candidate_id of this RerankCandidate.

        Stable identifier for the candidate document or answer.  # noqa: E501

        :param candidate_id: The candidate_id of this RerankCandidate.  # noqa: E501
        :type: str
        """
        if candidate_id is None:
            raise ValueError("Invalid value for `candidate_id`, must not be `None`")  # noqa: E501

        self._candidate_id = candidate_id

    @property
    def text(self):
        """Gets the text of this RerankCandidate.  # noqa: E501

        Candidate text to be reranked.  # noqa: E501

        :return: The text of this RerankCandidate.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this RerankCandidate.

        Candidate text to be reranked.  # noqa: E501

        :param text: The text of this RerankCandidate.  # noqa: E501
        :type: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def ranks(self):
        """Gets the ranks of this RerankCandidate.  # noqa: E501

        Mapping of upstream system identifiers to 1-based ranks.  # noqa: E501

        :return: The ranks of this RerankCandidate.  # noqa: E501
        :rtype: dict(str, int)
        """
        return self._ranks

    @ranks.setter
    def ranks(self, ranks):
        """Sets the ranks of this RerankCandidate.

        Mapping of upstream system identifiers to 1-based ranks.  # noqa: E501

        :param ranks: The ranks of this RerankCandidate.  # noqa: E501
        :type: dict(str, int)
        """

        self._ranks = ranks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RerankCandidate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RerankCandidate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
