# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RerankRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'query': 'str',
        'candidates': 'list[RerankCandidate]',
        'k': 'int',
        'top_n': 'int'
    }

    attribute_map = {
        'query': 'query',
        'candidates': 'candidates',
        'k': 'k',
        'top_n': 'top_n'
    }

    def __init__(self, query=None, candidates=None, k=60, top_n=None):  # noqa: E501
        """RerankRequest - a model defined in Swagger"""  # noqa: E501
        self._query = None
        self._candidates = None
        self._k = None
        self._top_n = None
        self.discriminator = None
        self.query = query
        self.candidates = candidates
        if k is not None:
            self.k = k
        if top_n is not None:
            self.top_n = top_n

    @property
    def query(self):
        """Gets the query of this RerankRequest.  # noqa: E501

        Query or instruction guiding the reranking.  # noqa: E501

        :return: The query of this RerankRequest.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this RerankRequest.

        Query or instruction guiding the reranking.  # noqa: E501

        :param query: The query of this RerankRequest.  # noqa: E501
        :type: str
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")  # noqa: E501

        self._query = query

    @property
    def candidates(self):
        """Gets the candidates of this RerankRequest.  # noqa: E501

        Candidate list to rerank.  # noqa: E501

        :return: The candidates of this RerankRequest.  # noqa: E501
        :rtype: list[RerankCandidate]
        """
        return self._candidates

    @candidates.setter
    def candidates(self, candidates):
        """Sets the candidates of this RerankRequest.

        Candidate list to rerank.  # noqa: E501

        :param candidates: The candidates of this RerankRequest.  # noqa: E501
        :type: list[RerankCandidate]
        """
        if candidates is None:
            raise ValueError("Invalid value for `candidates`, must not be `None`")  # noqa: E501
        if isinstance(candidates, list) and len(candidates) == 0:
            raise ValueError("`candidates` must not be empty for reranking")

        self._candidates = candidates

    @property
    def k(self):
        """Gets the k of this RerankRequest.  # noqa: E501

        RRF constant (usually 60).  # noqa: E501

        :return: The k of this RerankRequest.  # noqa: E501
        :rtype: int
        """
        return self._k

    @k.setter
    def k(self, k):
        """Sets the k of this RerankRequest.

        RRF constant (usually 60).  # noqa: E501

        :param k: The k of this RerankRequest.  # noqa: E501
        :type: int
        """

        if k is not None and k <= 0:
            raise ValueError("`k` must be positive for RRF computations")

        self._k = k

    @property
    def top_n(self):
        """Gets the top_n of this RerankRequest.  # noqa: E501

        Maximum number of results to return.  # noqa: E501

        :return: The top_n of this RerankRequest.  # noqa: E501
        :rtype: int
        """
        return self._top_n

    @top_n.setter
    def top_n(self, top_n):
        """Sets the top_n of this RerankRequest.

        Maximum number of results to return.  # noqa: E501

        :param top_n: The top_n of this RerankRequest.  # noqa: E501
        :type: int
        """
        if top_n is not None and top_n <= 0:
            raise ValueError("`top_n` must be positive if provided")

        self._top_n = top_n

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RerankRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RerankRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
