# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RerankResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'query': 'str',
        'k': 'int',
        'results': 'list[RerankResult]'
    }

    attribute_map = {
        'query': 'query',
        'k': 'k',
        'results': 'results'
    }

    def __init__(self, query=None, k=None, results=None):  # noqa: E501
        """RerankResponse - a model defined in Swagger"""  # noqa: E501
        self._query = None
        self._k = None
        self._results = None
        self.discriminator = None
        if query is not None:
            self.query = query
        if k is not None:
            self.k = k
        if results is not None:
            self.results = results

    @property
    def query(self):
        """Gets the query of this RerankResponse.  # noqa: E501

        Query or instruction guiding the reranking.  # noqa: E501

        :return: The query of this RerankResponse.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this RerankResponse.

        Query or instruction guiding the reranking.  # noqa: E501

        :param query: The query of this RerankResponse.  # noqa: E501
        :type: str
        """

        self._query = query

    @property
    def k(self):
        """Gets the k of this RerankResponse.  # noqa: E501

        RRF constant used for computation.  # noqa: E501

        :return: The k of this RerankResponse.  # noqa: E501
        :rtype: int
        """
        return self._k

    @k.setter
    def k(self, k):
        """Sets the k of this RerankResponse.

        RRF constant used for computation.  # noqa: E501

        :param k: The k of this RerankResponse.  # noqa: E501
        :type: int
        """

        self._k = k

    @property
    def results(self):
        """Gets the results of this RerankResponse.  # noqa: E501

        Reranked candidates with fused features.  # noqa: E501

        :return: The results of this RerankResponse.  # noqa: E501
        :rtype: list[RerankResult]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this RerankResponse.

        Reranked candidates with fused features.  # noqa: E501

        :param results: The results of this RerankResponse.  # noqa: E501
        :type: list[RerankResult]
        """

        self._results = results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RerankResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RerankResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
