# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RolesProfileResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'text_hash': 'str',
        'roles_profile': 'RolesProfile',
        'metadata': 'RolesProfileResponseMetadata'
    }

    attribute_map = {
        'version': 'version',
        'text_hash': 'text_hash',
        'roles_profile': 'roles_profile',
        'metadata': 'metadata'
    }

    def __init__(self, version=None, text_hash=None, roles_profile=None, metadata=None):  # noqa: E501
        """RolesProfileResponse - a model defined in Swagger"""  # noqa: E501
        self._version = None
        self._text_hash = None
        self._roles_profile = None
        self._metadata = None
        self.discriminator = None
        if version is not None:
            self.version = version
        if text_hash is not None:
            self.text_hash = text_hash
        if roles_profile is not None:
            self.roles_profile = roles_profile
        if metadata is not None:
            self.metadata = metadata

    @property
    def version(self):
        """Gets the version of this RolesProfileResponse.  # noqa: E501


        :return: The version of this RolesProfileResponse.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this RolesProfileResponse.


        :param version: The version of this RolesProfileResponse.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def text_hash(self):
        """Gets the text_hash of this RolesProfileResponse.  # noqa: E501

        Optional hash of the input text for idempotency/debugging.  # noqa: E501

        :return: The text_hash of this RolesProfileResponse.  # noqa: E501
        :rtype: str
        """
        return self._text_hash

    @text_hash.setter
    def text_hash(self, text_hash):
        """Sets the text_hash of this RolesProfileResponse.

        Optional hash of the input text for idempotency/debugging.  # noqa: E501

        :param text_hash: The text_hash of this RolesProfileResponse.  # noqa: E501
        :type: str
        """

        self._text_hash = text_hash

    @property
    def roles_profile(self):
        """Gets the roles_profile of this RolesProfileResponse.  # noqa: E501


        :return: The roles_profile of this RolesProfileResponse.  # noqa: E501
        :rtype: RolesProfile
        """
        return self._roles_profile

    @roles_profile.setter
    def roles_profile(self, roles_profile):
        """Sets the roles_profile of this RolesProfileResponse.


        :param roles_profile: The roles_profile of this RolesProfileResponse.  # noqa: E501
        :type: RolesProfile
        """

        self._roles_profile = roles_profile

    @property
    def metadata(self):
        """Gets the metadata of this RolesProfileResponse.  # noqa: E501


        :return: The metadata of this RolesProfileResponse.  # noqa: E501
        :rtype: RolesProfileResponseMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this RolesProfileResponse.


        :param metadata: The metadata of this RolesProfileResponse.  # noqa: E501
        :type: RolesProfileResponseMetadata
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RolesProfileResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RolesProfileResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
