# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RolesProfileRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'text': 'str',
        'normalize': 'bool',
        'return_full_vector': 'bool'
    }

    attribute_map = {
        'text': 'text',
        'normalize': 'normalize',
        'return_full_vector': 'return_full_vector'
    }

    def __init__(self, text=None, normalize=True, return_full_vector=True):  # noqa: E501
        """RolesProfileRequest - a model defined in Swagger"""  # noqa: E501
        self._text = None
        self._normalize = None
        self._return_full_vector = None
        self.discriminator = None
        self.text = text
        if normalize is not None:
            self.normalize = normalize
        if return_full_vector is not None:
            self.return_full_vector = return_full_vector

    @property
    def text(self):
        """Gets the text of this RolesProfileRequest.  # noqa: E501

        Text to analyze.  # noqa: E501

        :return: The text of this RolesProfileRequest.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this RolesProfileRequest.

        Text to analyze.  # noqa: E501

        :param text: The text of this RolesProfileRequest.  # noqa: E501
        :type: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def normalize(self):
        """Gets the normalize of this RolesProfileRequest.  # noqa: E501

        Whether to apply softmax/normalization over roles.  # noqa: E501

        :return: The normalize of this RolesProfileRequest.  # noqa: E501
        :rtype: bool
        """
        return self._normalize

    @normalize.setter
    def normalize(self, normalize):
        """Sets the normalize of this RolesProfileRequest.

        Whether to apply softmax/normalization over roles.  # noqa: E501

        :param normalize: The normalize of this RolesProfileRequest.  # noqa: E501
        :type: bool
        """

        self._normalize = normalize

    @property
    def return_full_vector(self):
        """Gets the return_full_vector of this RolesProfileRequest.  # noqa: E501

        Whether to return the full vector of role weights.  # noqa: E501

        :return: The return_full_vector of this RolesProfileRequest.  # noqa: E501
        :rtype: bool
        """
        return self._return_full_vector

    @return_full_vector.setter
    def return_full_vector(self, return_full_vector):
        """Sets the return_full_vector of this RolesProfileRequest.

        Whether to return the full vector of role weights.  # noqa: E501

        :param return_full_vector: The return_full_vector of this RolesProfileRequest.  # noqa: E501
        :type: bool
        """

        self._return_full_vector = return_full_vector

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RolesProfileRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RolesProfileRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
