# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RolesProfileResponseMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'processing_time_ms': 'int'
    }

    attribute_map = {
        'processing_time_ms': 'processing_time_ms'
    }

    def __init__(self, processing_time_ms=None):  # noqa: E501
        """RolesProfileResponseMetadata - a model defined in Swagger"""  # noqa: E501
        self._processing_time_ms = None
        self.discriminator = None
        if processing_time_ms is not None:
            self.processing_time_ms = processing_time_ms

    @property
    def processing_time_ms(self):
        """Gets the processing_time_ms of this RolesProfileResponseMetadata.  # noqa: E501


        :return: The processing_time_ms of this RolesProfileResponseMetadata.  # noqa: E501
        :rtype: int
        """
        return self._processing_time_ms

    @processing_time_ms.setter
    def processing_time_ms(self, processing_time_ms):
        """Sets the processing_time_ms of this RolesProfileResponseMetadata.


        :param processing_time_ms: The processing_time_ms of this RolesProfileResponseMetadata.  # noqa: E501
        :type: int
        """

        self._processing_time_ms = processing_time_ms

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RolesProfileResponseMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RolesProfileResponseMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
