# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RolesProfile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'roles': 'list[str]',
        'weights': 'list[float]',
        'top_roles': 'list[RolesProfileTopRoles]'
    }

    attribute_map = {
        'roles': 'roles',
        'weights': 'weights',
        'top_roles': 'top_roles'
    }

    def __init__(self, roles=None, weights=None, top_roles=None):  # noqa: E501
        """RolesProfile - a model defined in Swagger"""  # noqa: E501
        self._roles = None
        self._weights = None
        self._top_roles = None
        self.discriminator = None
        if roles is not None:
            self.roles = roles
        if weights is not None:
            self.weights = weights
        if top_roles is not None:
            self.top_roles = top_roles

    @property
    def roles(self):
        """Gets the roles of this RolesProfile.  # noqa: E501


        :return: The roles of this RolesProfile.  # noqa: E501
        :rtype: list[str]
        """
        return self._roles

    @roles.setter
    def roles(self, roles):
        """Sets the roles of this RolesProfile.


        :param roles: The roles of this RolesProfile.  # noqa: E501
        :type: list[str]
        """

        self._roles = roles

    @property
    def weights(self):
        """Gets the weights of this RolesProfile.  # noqa: E501

        Relative weight of each role (often normalized to sum ~1).  # noqa: E501

        :return: The weights of this RolesProfile.  # noqa: E501
        :rtype: list[float]
        """
        return self._weights

    @weights.setter
    def weights(self, weights):
        """Sets the weights of this RolesProfile.

        Relative weight of each role (often normalized to sum ~1).  # noqa: E501

        :param weights: The weights of this RolesProfile.  # noqa: E501
        :type: list[float]
        """

        self._weights = weights

    @property
    def top_roles(self):
        """Gets the top_roles of this RolesProfile.  # noqa: E501

        Top roles with highest weights.  # noqa: E501

        :return: The top_roles of this RolesProfile.  # noqa: E501
        :rtype: list[RolesProfileTopRoles]
        """
        return self._top_roles

    @top_roles.setter
    def top_roles(self, top_roles):
        """Sets the top_roles of this RolesProfile.

        Top roles with highest weights.  # noqa: E501

        :param top_roles: The top_roles of this RolesProfile.  # noqa: E501
        :type: list[RolesProfileTopRoles]
        """

        self._top_roles = top_roles

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RolesProfile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RolesProfile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
