# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SavantQualityMetrics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'phi': 'float',
        'omega': 'float',
        'srrf': 'float',
        'crrf': 'float',
        'e_h': 'float',
        'meta_score': 'float',
        'label': 'str',
        'explanation': 'str'
    }

    attribute_map = {
        'phi': 'phi',
        'omega': 'omega',
        'srrf': 'SRRF',
        'crrf': 'CRRF',
        'e_h': 'E_H',
        'meta_score': 'meta_score',
        'label': 'label',
        'explanation': 'explanation'
    }

    def __init__(self, phi=None, omega=None, srrf=None, crrf=None, e_h=None, meta_score=None, label=None, explanation=None):  # noqa: E501
        """SavantQualityMetrics - a model defined in Swagger"""  # noqa: E501
        self._phi = None
        self._omega = None
        self._srrf = None
        self._crrf = None
        self._e_h = None
        self._meta_score = None
        self._label = None
        self._explanation = None
        self.discriminator = None
        if phi is not None:
            self.phi = phi
        if omega is not None:
            self.omega = omega
        if srrf is not None:
            self.srrf = srrf
        if crrf is not None:
            self.crrf = crrf
        if e_h is not None:
            self.e_h = e_h
        if meta_score is not None:
            self.meta_score = meta_score
        if label is not None:
            self.label = label
        if explanation is not None:
            self.explanation = explanation

    @property
    def phi(self):
        """Gets the phi of this SavantQualityMetrics.  # noqa: E501

        Φ – conceptual resonance score.  # noqa: E501

        :return: The phi of this SavantQualityMetrics.  # noqa: E501
        :rtype: float
        """
        return self._phi

    @phi.setter
    def phi(self, phi):
        """Sets the phi of this SavantQualityMetrics.

        Φ – conceptual resonance score.  # noqa: E501

        :param phi: The phi of this SavantQualityMetrics.  # noqa: E501
        :type: float
        """

        self._phi = phi

    @property
    def omega(self):
        """Gets the omega of this SavantQualityMetrics.  # noqa: E501

        Ω – oscillatory/stability indicator.  # noqa: E501

        :return: The omega of this SavantQualityMetrics.  # noqa: E501
        :rtype: float
        """
        return self._omega

    @omega.setter
    def omega(self, omega):
        """Sets the omega of this SavantQualityMetrics.

        Ω – oscillatory/stability indicator.  # noqa: E501

        :param omega: The omega of this SavantQualityMetrics.  # noqa: E501
        :type: float
        """

        self._omega = omega

    @property
    def srrf(self):
        """Gets the srrf of this SavantQualityMetrics.  # noqa: E501

        Spectral RRF coherence metric.  # noqa: E501

        :return: The srrf of this SavantQualityMetrics.  # noqa: E501
        :rtype: float
        """
        return self._srrf

    @srrf.setter
    def srrf(self, srrf):
        """Sets the srrf of this SavantQualityMetrics.

        Spectral RRF coherence metric.  # noqa: E501

        :param srrf: The srrf of this SavantQualityMetrics.  # noqa: E501
        :type: float
        """

        self._srrf = srrf

    @property
    def crrf(self):
        """Gets the crrf of this SavantQualityMetrics.  # noqa: E501

        Conceptual RRF coherence metric.  # noqa: E501

        :return: The crrf of this SavantQualityMetrics.  # noqa: E501
        :rtype: float
        """
        return self._crrf

    @crrf.setter
    def crrf(self, crrf):
        """Sets the crrf of this SavantQualityMetrics.

        Conceptual RRF coherence metric.  # noqa: E501

        :param crrf: The crrf of this SavantQualityMetrics.  # noqa: E501
        :type: float
        """

        self._crrf = crrf

    @property
    def e_h(self):
        """Gets the e_h of this SavantQualityMetrics.  # noqa: E501

        Effective entropy / Harmony metric.  # noqa: E501

        :return: The e_h of this SavantQualityMetrics.  # noqa: E501
        :rtype: float
        """
        return self._e_h

    @e_h.setter
    def e_h(self, e_h):
        """Sets the e_h of this SavantQualityMetrics.

        Effective entropy / Harmony metric.  # noqa: E501

        :param e_h: The e_h of this SavantQualityMetrics.  # noqa: E501
        :type: float
        """

        self._e_h = e_h

    @property
    def meta_score(self):
        """Gets the meta_score of this SavantQualityMetrics.  # noqa: E501

        Meta-classifier quality score (e.g., 0–1).  # noqa: E501

        :return: The meta_score of this SavantQualityMetrics.  # noqa: E501
        :rtype: float
        """
        return self._meta_score

    @meta_score.setter
    def meta_score(self, meta_score):
        """Sets the meta_score of this SavantQualityMetrics.

        Meta-classifier quality score (e.g., 0–1).  # noqa: E501

        :param meta_score: The meta_score of this SavantQualityMetrics.  # noqa: E501
        :type: float
        """

        self._meta_score = meta_score

    @property
    def label(self):
        """Gets the label of this SavantQualityMetrics.  # noqa: E501

        Discrete label derived from meta_score.  # noqa: E501

        :return: The label of this SavantQualityMetrics.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this SavantQualityMetrics.

        Discrete label derived from meta_score.  # noqa: E501

        :param label: The label of this SavantQualityMetrics.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def explanation(self):
        """Gets the explanation of this SavantQualityMetrics.  # noqa: E501

        Human-readable explanation of the quality.  # noqa: E501

        :return: The explanation of this SavantQualityMetrics.  # noqa: E501
        :rtype: str
        """
        return self._explanation

    @explanation.setter
    def explanation(self, explanation):
        """Sets the explanation of this SavantQualityMetrics.

        Human-readable explanation of the quality.  # noqa: E501

        :param explanation: The explanation of this SavantQualityMetrics.  # noqa: E501
        :type: str
        """

        self._explanation = explanation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SavantQualityMetrics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SavantQualityMetrics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
