# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TutorRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'question': 'str',
        'student_level': 'str',
        'language': 'str',
        'max_new_tokens': 'int',
        'include_roles_profile': 'bool',
        'include_candidates': 'bool',
        'metadata': 'dict(str, object)'
    }

    attribute_map = {
        'question': 'question',
        'student_level': 'student_level',
        'language': 'language',
        'max_new_tokens': 'max_new_tokens',
        'include_roles_profile': 'include_roles_profile',
        'include_candidates': 'include_candidates',
        'metadata': 'metadata'
    }

    def __init__(self, question=None, student_level='undergrad', language='en', max_new_tokens=256, include_roles_profile=True, include_candidates=False, metadata=None):  # noqa: E501
        """TutorRequest - a model defined in Swagger"""  # noqa: E501
        self._question = None
        self._student_level = None
        self._language = None
        self._max_new_tokens = None
        self._include_roles_profile = None
        self._include_candidates = None
        self._metadata = None
        self.discriminator = None
        self.question = question
        if student_level is not None:
            self.student_level = student_level
        if language is not None:
            self.language = language
        if max_new_tokens is not None:
            self.max_new_tokens = max_new_tokens
        if include_roles_profile is not None:
            self.include_roles_profile = include_roles_profile
        if include_candidates is not None:
            self.include_candidates = include_candidates
        if metadata is not None:
            self.metadata = metadata

    @property
    def question(self):
        """Gets the question of this TutorRequest.  # noqa: E501

        Scientific or RRF-related question to be answered.  # noqa: E501

        :return: The question of this TutorRequest.  # noqa: E501
        :rtype: str
        """
        return self._question

    @question.setter
    def question(self, question):
        """Sets the question of this TutorRequest.

        Scientific or RRF-related question to be answered.  # noqa: E501

        :param question: The question of this TutorRequest.  # noqa: E501
        :type: str
        """
        if question is None:
            raise ValueError("Invalid value for `question`, must not be `None`")  # noqa: E501

        self._question = question

    @property
    def student_level(self):
        """Gets the student_level of this TutorRequest.  # noqa: E501

        Target level of the explanation.  # noqa: E501

        :return: The student_level of this TutorRequest.  # noqa: E501
        :rtype: str
        """
        return self._student_level

    @student_level.setter
    def student_level(self, student_level):
        """Sets the student_level of this TutorRequest.

        Target level of the explanation.  # noqa: E501

        :param student_level: The student_level of this TutorRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["highschool", "undergrad", "grad", "researcher"]  # noqa: E501
        if student_level not in allowed_values:
            raise ValueError(
                "Invalid value for `student_level` ({0}), must be one of {1}"  # noqa: E501
                .format(student_level, allowed_values)
            )

        self._student_level = student_level

    @property
    def language(self):
        """Gets the language of this TutorRequest.  # noqa: E501

        Language code guiding the answer style.  # noqa: E501

        :return: The language of this TutorRequest.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this TutorRequest.

        Language code guiding the answer style.  # noqa: E501

        :param language: The language of this TutorRequest.  # noqa: E501
        :type: str
        """

        self._language = language

    @property
    def max_new_tokens(self):
        """Gets the max_new_tokens of this TutorRequest.  # noqa: E501

        Maximum number of tokens to generate for the answer.  # noqa: E501

        :return: The max_new_tokens of this TutorRequest.  # noqa: E501
        :rtype: int
        """
        return self._max_new_tokens

    @max_new_tokens.setter
    def max_new_tokens(self, max_new_tokens):
        """Sets the max_new_tokens of this TutorRequest.

        Maximum number of tokens to generate for the answer.  # noqa: E501

        :param max_new_tokens: The max_new_tokens of this TutorRequest.  # noqa: E501
        :type: int
        """

        self._max_new_tokens = max_new_tokens

    @property
    def include_roles_profile(self):
        """Gets the include_roles_profile of this TutorRequest.  # noqa: E501

        Whether to include the icosahedral roles profile in the response.  # noqa: E501

        :return: The include_roles_profile of this TutorRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_roles_profile

    @include_roles_profile.setter
    def include_roles_profile(self, include_roles_profile):
        """Sets the include_roles_profile of this TutorRequest.

        Whether to include the icosahedral roles profile in the response.  # noqa: E501

        :param include_roles_profile: The include_roles_profile of this TutorRequest.  # noqa: E501
        :type: bool
        """

        self._include_roles_profile = include_roles_profile

    @property
    def include_candidates(self):
        """Gets the include_candidates of this TutorRequest.  # noqa: E501

        Whether to include internal candidate answers and their metrics.  # noqa: E501

        :return: The include_candidates of this TutorRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_candidates

    @include_candidates.setter
    def include_candidates(self, include_candidates):
        """Sets the include_candidates of this TutorRequest.

        Whether to include internal candidate answers and their metrics.  # noqa: E501

        :param include_candidates: The include_candidates of this TutorRequest.  # noqa: E501
        :type: bool
        """

        self._include_candidates = include_candidates

    @property
    def metadata(self):
        """Gets the metadata of this TutorRequest.  # noqa: E501

        Optional metadata for client-side tracking (session_id, user_id, etc).  # noqa: E501

        :return: The metadata of this TutorRequest.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this TutorRequest.

        Optional metadata for client-side tracking (session_id, user_id, etc).  # noqa: E501

        :param metadata: The metadata of this TutorRequest.  # noqa: E501
        :type: dict(str, object)
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TutorRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TutorRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
