# coding: utf-8

"""
    Savant RRF API

    Savant RRF v1.0 (Phi9_4) – Scientific tutoring, conceptual quality evaluation, and icosahedral role profiling for STEM and RRF-related text.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TutorResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'question': 'str',
        'answer': 'str',
        'student_level': 'str',
        'language': 'str',
        'quality': 'SavantQualityMetrics',
        'roles_profile': 'AllOfTutorResponseRolesProfile',
        'candidates': 'list[TutorResponseCandidates]',
        'metadata': 'dict(str, object)'
    }

    attribute_map = {
        'version': 'version',
        'question': 'question',
        'answer': 'answer',
        'student_level': 'student_level',
        'language': 'language',
        'quality': 'quality',
        'roles_profile': 'roles_profile',
        'candidates': 'candidates',
        'metadata': 'metadata'
    }

    def __init__(self, version=None, question=None, answer=None, student_level=None, language=None, quality=None, roles_profile=None, candidates=None, metadata=None):  # noqa: E501
        """TutorResponse - a model defined in Swagger"""  # noqa: E501
        self._version = None
        self._question = None
        self._answer = None
        self._student_level = None
        self._language = None
        self._quality = None
        self._roles_profile = None
        self._candidates = None
        self._metadata = None
        self.discriminator = None
        if version is not None:
            self.version = version
        if question is not None:
            self.question = question
        if answer is not None:
            self.answer = answer
        if student_level is not None:
            self.student_level = student_level
        if language is not None:
            self.language = language
        if quality is not None:
            self.quality = quality
        if roles_profile is not None:
            self.roles_profile = roles_profile
        if candidates is not None:
            self.candidates = candidates
        if metadata is not None:
            self.metadata = metadata

    @property
    def version(self):
        """Gets the version of this TutorResponse.  # noqa: E501


        :return: The version of this TutorResponse.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this TutorResponse.


        :param version: The version of this TutorResponse.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def question(self):
        """Gets the question of this TutorResponse.  # noqa: E501


        :return: The question of this TutorResponse.  # noqa: E501
        :rtype: str
        """
        return self._question

    @question.setter
    def question(self, question):
        """Sets the question of this TutorResponse.


        :param question: The question of this TutorResponse.  # noqa: E501
        :type: str
        """

        self._question = question

    @property
    def answer(self):
        """Gets the answer of this TutorResponse.  # noqa: E501


        :return: The answer of this TutorResponse.  # noqa: E501
        :rtype: str
        """
        return self._answer

    @answer.setter
    def answer(self, answer):
        """Sets the answer of this TutorResponse.


        :param answer: The answer of this TutorResponse.  # noqa: E501
        :type: str
        """

        self._answer = answer

    @property
    def student_level(self):
        """Gets the student_level of this TutorResponse.  # noqa: E501


        :return: The student_level of this TutorResponse.  # noqa: E501
        :rtype: str
        """
        return self._student_level

    @student_level.setter
    def student_level(self, student_level):
        """Sets the student_level of this TutorResponse.


        :param student_level: The student_level of this TutorResponse.  # noqa: E501
        :type: str
        """

        self._student_level = student_level

    @property
    def language(self):
        """Gets the language of this TutorResponse.  # noqa: E501


        :return: The language of this TutorResponse.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this TutorResponse.


        :param language: The language of this TutorResponse.  # noqa: E501
        :type: str
        """

        self._language = language

    @property
    def quality(self):
        """Gets the quality of this TutorResponse.  # noqa: E501


        :return: The quality of this TutorResponse.  # noqa: E501
        :rtype: SavantQualityMetrics
        """
        return self._quality

    @quality.setter
    def quality(self, quality):
        """Sets the quality of this TutorResponse.


        :param quality: The quality of this TutorResponse.  # noqa: E501
        :type: SavantQualityMetrics
        """

        self._quality = quality

    @property
    def roles_profile(self):
        """Gets the roles_profile of this TutorResponse.  # noqa: E501


        :return: The roles_profile of this TutorResponse.  # noqa: E501
        :rtype: AllOfTutorResponseRolesProfile
        """
        return self._roles_profile

    @roles_profile.setter
    def roles_profile(self, roles_profile):
        """Sets the roles_profile of this TutorResponse.


        :param roles_profile: The roles_profile of this TutorResponse.  # noqa: E501
        :type: AllOfTutorResponseRolesProfile
        """

        self._roles_profile = roles_profile

    @property
    def candidates(self):
        """Gets the candidates of this TutorResponse.  # noqa: E501

        Optional internal candidates and their quality metrics.  # noqa: E501

        :return: The candidates of this TutorResponse.  # noqa: E501
        :rtype: list[TutorResponseCandidates]
        """
        return self._candidates

    @candidates.setter
    def candidates(self, candidates):
        """Sets the candidates of this TutorResponse.

        Optional internal candidates and their quality metrics.  # noqa: E501

        :param candidates: The candidates of this TutorResponse.  # noqa: E501
        :type: list[TutorResponseCandidates]
        """

        self._candidates = candidates

    @property
    def metadata(self):
        """Gets the metadata of this TutorResponse.  # noqa: E501


        :return: The metadata of this TutorResponse.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this TutorResponse.


        :param metadata: The metadata of this TutorResponse.  # noqa: E501
        :type: dict(str, object)
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TutorResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TutorResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
